name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: SHentx
        password: scm110110

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: your-docker-hub-username/your-image-name:$(date +%s)

    - name: Create Git tag
      run: |
        IMAGE_TAG=your-image-name-$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        git tag $IMAGE_TAG
        git push origin $IMAGE_TAG

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        tag_name: ${{ env.IMAGE_TAG }}
        name: Release ${{ env.IMAGE_TAG }}
        body: "Release of ${{ env.IMAGE_TAG }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
